services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: http://localhost:5003
        VITE_IMAGES_CDN_URL: https://images.careerseason.com
    ports:
      - 5173:3000
    